import org.gradle.kotlin.dsl.repositories

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.4/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("application")
    id("com.github.ben-manes.versions") version "0.54.0"
    id("org.sonarqube") version "7.3.0.8198"
    id("checkstyle")
}

group = "hexlet.code"
version = "1.0-SNAPSHOT"

application {
    mainClass.set("hexlet.code.App")
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
}

tasks.jar {
    manifest {
        attributes("Main-Class" to "hexlet.code.App")
    }

    val runtimeClasspath = configurations.runtimeClasspath.get()

    from({
        runtimeClasspath.map { if (it.isDirectory) it else zipTree(it) }
    })

    // Дубликаты файлов могут возникнуть при распаковке зависимостей
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

application {
    mainClass.set("hexlet.code.App")
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

sonar {
    properties {
        property("sonar.projectKey", "GarryHuman_java-project-61")
        property("sonar.organization", "garryhuman")
    }
}

checkstyle {
    toolVersion = "10.21.4"
    configFile = rootProject.file("config/checkstyle/checkstyle.xml")
    isIgnoreFailures = false
}